<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Square" Version="42.0.2" />
    <PackageReference Include="Stripe.net" Version="49.0.0" />
  </ItemGroup>

</Project>
